### ISSUE TITLE
Dependency Version Mismatch Requires Specification

### ISSUE THREAD

**Issue by ngc-shj** [lihxxx/DisPose#10]
**Overview of the Issue**  
When running `inference_ctrl.py`, errors due to version mismatches were encountered:

1. `huggingface_hub`: Version mismatch caused `ImportError: cannot import name 'cached_download'`.
2. `av`: Version mismatch resulted in `TypeError: an integer is required`.
    - This aligns with the problem reported in [Tencent/MimicMotion Issue #105](https://github.com/Tencent/MimicMotion/issues/105), where similar errors were discussed and resolved by specifying appropriate package versions.

**Solution**  
The following version specifications resolved the issue:

```bash
# Resolving version mismatch for huggingface_hub
pip install huggingface_hub==0.25.2

# Resolving version mismatch for av
pip install av==12.0.0
```

**Comment by lihxxx** [comment]
We have updated the [requirements.txt](https://github.com/lihxxx/DisPose/commit/c0a87d21ebfd1b0d37c75cee994900717e498b28) to fix the version conflict.
