### ISSUE TITLE
ImportError: cannot import name 'ASPECT_RATIO' from 'constants

### ISSUE THREAD

**Issue by tanshuai0219** [lihxxx/DisPose#5]
When running the code, I encountered this error: 'ImportError: cannot import name 'ASPECT_RATIO' from 'constants' (/root/miniconda3/lib/python3.10/site-packages/constants.py)'. Although I have already installed 'constants', could you specify the version of 'constants'?

**Comment by lihx-me** [comment]
Hi, we have updated constants.py. It is a local file that specifies the video ratio.
